### ISSUE TITLE
Glissando line missing

### ISSUE THREAD

**Issue by annawright18** [polyrhythm-project/polyrhythm-website#104]
Soprano in Berg 456 - R456B_Ber-w15p474-475m553-557

<img width="361" alt="Screen Shot 2020-02-05 at 7 10 31 PM" src="https://user-images.githubusercontent.com/54776443/73902624-45dbc800-484b-11ea-89fa-5d01165ad87d.png">
<img width="784" alt="Screen Shot 2020-02-05 at 7 10 25 PM" src="https://user-images.githubusercontent.com/54776443/73902625-47a58b80-484b-11ea-9b69-2277c6bd05a5.png">

**Comment by craigsapp** [comment]
Same as issue #61
