### ISSUE TITLE
Rehearsal marks not transferring

### ISSUE THREAD

**Issue by annawright18** [polyrhythm-project/polyrhythm-website#111]
Rehearsal marks not appearing

Example 647

<img width="725" alt="Screen Shot 2020-02-14 at 3 41 17 PM" src="https://user-images.githubusercontent.com/54776443/74576635-8c62ae00-4f40-11ea-8d7c-15935baba3b9.png">
<img width="727" alt="Screen Shot 2020-02-14 at 3 41 26 PM" src="https://user-images.githubusercontent.com/54776443/74576638-8d93db00-4f40-11ea-962d-83d9d6351710.png">

**Comment by craigsapp** [comment]
Same as issue #77
