### ISSUE TITLE
Ties - Horizontal spacing

### ISSUE THREAD

**Issue by aaronearlgraham** [polyrhythm-project/polyrhythm-website#112]
T564, Martin - horizontal spacing is causing some ties to be crushed very close together

SIB:
![image](https://user-images.githubusercontent.com/59717186/74690646-af859b80-5194-11ea-86ed-57940c68fd8d.png)

VHV
![image](https://user-images.githubusercontent.com/59717186/74690650-b6141300-5194-11ea-80e4-cccd046f1eff.png)

**Comment by craigsapp** [comment]
This will be dependent on the spacing/size of the music in verovio (so not controllable from Sibelius or Humdrum).

This problem is submitted to verovio as issue https://github.com/rism-ch/verovio/issues/1310
