### ISSUE TITLE
Recordings page

### ISSUE THREAD

**Issue by epoudrier** [polyrhythm-project/polyrhythm-website#135]
On the Recordings page, users will be able to get information about the Naxos audio used for each example as well has access to the recording (if they have a Naxos subscription). Here is the format:

```
Janáček, Leoš [Heading]

[drop-down] Jan-4 "Work Title" (Composition Year)
Example Rxxx
      A0 Recording Album Title, A0 Recording Label, A0 Recording Catalogue No., A0 Release Year, A0 Naxos Recording URL
      Example Start Time, Example End Time
Example Txxx
      A0 Recording Album Title, A0 Recording Label, A0 Recording Catalogue No., A0 Release Year, A0 Naxos Recording URL
      Example Start Time, Example End Time

```
 
Work will be a drop-down for each work, with the examples and metadata listed under. We could allow sorting by Work ID and Composition Year.

**Comment by craigsapp** [comment]
Initial implementation is done:

<img width="1208" alt="Screen Shot 2022-06-23 at 7 44 20 PM" src="https://user-images.githubusercontent.com/3487289/175451812-1503398b-b932-44f9-ac7b-8bb3d6977652.png">

The main thing to add are the start/end/duration data for the examples (which are on the main metadata spreadsheet).

**Comment by epoudrier** [comment]
This has been done.
