### ISSUE TITLE
Missing Composer Name on VHV all files (Rendering Error)

### ISSUE THREAD

**Issue by cdf75ubc** [polyrhythm-project/polyrhythm-website#22]
ex. T323, Bartok, VHV does not show composer name from SIB .pdf

**Comment by cdf75ubc** [comment]
for all files

**Comment by epoudrier** [comment]
This is not a rendering issue. If the name is missing on the Sibelius generated PDF, it should be added during the editing phase. Make a note in the "Transcription Errors" column in the spreadsheet.
