### ISSUE TITLE
Tuplet number problem

### ISSUE THREAD

**Issue by craigsapp** [polyrhythm-project/polyrhythm-website#39]
Example 744 has tuplet problems on the first tuplet group of a measure:

https://polyrhythm.humdrum.org/example/?id=744

<img width="462" alt="Screen Shot 2020-01-18 at 14 57 45" src="https://user-images.githubusercontent.com/3487289/72671692-e4ba9480-3a02-11ea-8013-42565c09337f.png">

probably related to previous tuplet problems.

**Comment by craigsapp** [comment]
Added to verovio-humdrum-viewer repository issues: https://github.com/humdrum-tools/verovio-humdrum-viewer/issues/262

**Comment by aaronearlgraham** [comment]
T706, Copland, cello, mm. 1, tuplet numbering issues, slur is rendered up to violin staff, beaming issues

**Comment by epoudrier** [comment]
Refer to updated protocol. If issue already created (tuplets) add to spreadsheet only. Don’t mix types (slur, beaming).

**Comment by craigsapp** [comment]
Now seems to be fix:

<img width="439" alt="Screen Shot 2020-01-19 at 22 15 45" src="https://user-images.githubusercontent.com/3487289/72702993-4402cc80-3b09-11ea-8179-038bf43ff357.png">

The problem was that an older version of verovio was being used from before the version that fixes the problem.
