### ISSUE TITLE
Missing Slur/Tie

### ISSUE THREAD

**Issue by rafaperlau** [polyrhythm-project/polyrhythm-website#57]
Ex. T793, Britten, Oboe, bar 6: missing slur at beat 4 on VHV.

VHV:

![Sem título 1](https://user-images.githubusercontent.com/59910404/72946908-3467cb80-3d35-11ea-9c79-dd5f4bb68c1b.jpg)

Sibelius PDF:

![Sem título 2](https://user-images.githubusercontent.com/59910404/72946920-3f226080-3d35-11ea-892d-942b43c0c1ff.jpg)

**Comment by rafaperlau** [comment]
Ex. T793, Britten, Violoncello, bar 6: missing slur starting at beat 3.

VHV:

![Sem título 1](https://user-images.githubusercontent.com/59910404/72948118-143a0b80-3d39-11ea-9c98-ccbf84c3cafa.jpg)


Sibelius PDF:

![Sem título 2](https://user-images.githubusercontent.com/59910404/72948126-19975600-3d39-11ea-8b07-ca1c617a4f98.jpg)

**Comment by craigsapp** [comment]
This is the same as issue #13.  The problem is that when a slur goes off of the end of the example it is currently not being included in the conversion. (or when a slur starts before the first note).

https://polyrhythm.humdrum.org/example/?id=T793
