### ISSUE TITLE
Piano bass clef missing

### ISSUE THREAD

**Issue by cdf75ubc** [polyrhythm-project/polyrhythm-website#63]
T337, Bartok, Piano Concerto #1, I believe it is a bracket/staff related issue: the score contais a bass clef for the solo piano part, but it is blank. In the VHV, the bass clef is supressed, piano staff name disapperars, and staff name "horn in f" now includes the piano part:

<img width="578" alt="Screen Shot 2020-01-23 at 5 16 13 PM" src="https://user-images.githubusercontent.com/59900770/73037479-174dfe00-3e04-11ea-9785-5c1a61cf6cad.png">

<img width="617" alt="Screen Shot 2020-01-23 at 5 16 45 PM" src="https://user-images.githubusercontent.com/59900770/73037498-2b91fb00-3e04-11ea-849d-bb9490453c5e.png">

**Comment by craigsapp** [comment]
This is the same as issue https://github.com/polyrhythm-project/polyrhythm-website/issues/54
