### ISSUE TITLE
accented staccatos (> + .) not clear

### ISSUE THREAD

**Issue by cdf75ubc** [polyrhythm-project/polyrhythm-website#64]
T337, Bartok, Piano Concerto #1, for many of the strings accented staccato markings (> + .) are "colliding":

<img width="1376" alt="Screen Shot 2020-01-23 at 5 33 32 PM" src="https://user-images.githubusercontent.com/59900770/73038438-4e71de80-3e07-11ea-9fb9-4fbd7485b2ae.png">

**Comment by craigsapp** [comment]
This is the same as issue https://github.com/polyrhythm-project/polyrhythm-website/issues/58 (so closing this one).

This is reported as verovio issue https://github.com/rism-ch/verovio/issues/572#issuecomment-578056218
