### ISSUE TITLE
Notes in wrong octave

### ISSUE THREAD

**Issue by rafaperlau** [polyrhythm-project/polyrhythm-website#66]
Ex. T794, Britten, Contrabass: instrument is written on the wrong octave.

VHV error:
![Sem título 1](https://user-images.githubusercontent.com/59910404/73091443-4cebf900-3e8f-11ea-8f80-3360737097fc.jpg)

Sibelius PDF:
![Sem título 2](https://user-images.githubusercontent.com/59910404/73091461-570df780-3e8f-11ea-8d2d-254d2c903f38.jpg)

![Sem título 3](https://user-images.githubusercontent.com/59910404/73091477-5e350580-3e8f-11ea-8ebf-530f08806de9.jpg)

**Comment by craigsapp** [comment]
This is the same as issue https://github.com/polyrhythm-project/polyrhythm-website/issues/20
