### ISSUE TITLE
Instrument Bracketing

### ISSUE THREAD

**Issue by Boardbreak** [polyrhythm-project/polyrhythm-website#67]
Percussion is bracketed with the harp; should be separated. 

VHV:

![Incorrect Bracketing](https://user-images.githubusercontent.com/59404234/73094571-b2db7f00-3e95-11ea-86d7-6651c1d7f218.png)

Desired Rendering:

![Correct Bracketing](https://user-images.githubusercontent.com/59404234/73094600-c38bf500-3e95-11ea-9682-19c4870d309e.png)

**Comment by craigsapp** [comment]
same as #28
