### ISSUE TITLE
Wrong Note 

### ISSUE THREAD

**Issue by Boardbreak** [polyrhythm-project/polyrhythm-website#69]
In Berg T437, Horn 1 in on the first beat of mm. 2 should be F# 4, not F 4, along with the second eighth of beat 3 in mm. 2.   The rest of the incorrect notes are listed on the spreadsheet.

VHV:

![F 4 (incorrect)](https://user-images.githubusercontent.com/59404234/73096407-8cb7de00-3e99-11ea-81fe-a5c8605ff2dd.png)

Desired Rendering:

![F# 4 (correct)](https://user-images.githubusercontent.com/59404234/73096229-2f239180-3e99-11ea-9c47-dad5f85fc6c0.png)

**Comment by craigsapp** [comment]
Am I supposed to guess the example number (out of 800)? 😝 

It is T437: https://polyrhythm.humdrum.org/example/?id=437

This is issue https://github.com/polyrhythm-project/polyrhythm-website/issues/26
