### ISSUE TITLE
Missing instrument name

### ISSUE THREAD

**Issue by rafaperlau** [polyrhythm-project/polyrhythm-website#70]
Ex. T796, Britten: missing instrument name for the piano.

VHV error:
![Sem título 1](https://user-images.githubusercontent.com/59910404/73097652-837c4080-3e9c-11ea-8fd2-2fbe42026dd1.jpg)

Sibelius PDF:
![Sem título 2](https://user-images.githubusercontent.com/59910404/73097660-8a0ab800-3e9c-11ea-9103-4998c996ca6d.jpg)

**Comment by craigsapp** [comment]
This is issue https://github.com/polyrhythm-project/polyrhythm-website/issues/54 (grand-staff resting staves are being removed, but they should not be removed).
