### ISSUE TITLE
Drums/piano staffs combined

### ISSUE THREAD

**Issue by annawright18** [polyrhythm-project/polyrhythm-website#72]
Gershwin: R686_Ger-w3p12h9m1-5

Piano staff combined weirdly into drum/piano, drum line blank

<img width="344" alt="Screen Shot 2020-01-24 at 2 53 55 PM" src="https://user-images.githubusercontent.com/54776443/73109912-73268e80-3eb9-11ea-8f98-b5620c7bc04e.png">

<img width="614" alt="Screen Shot 2020-01-24 at 2 54 02 PM" src="https://user-images.githubusercontent.com/54776443/73109916-7588e880-3eb9-11ea-94bf-5936b180d771.png">

**Comment by craigsapp** [comment]
This is the same as issue #54.
