### ISSUE TITLE
Missing tremolos

### ISSUE THREAD

**Issue by annawright18** [polyrhythm-project/polyrhythm-website#76]
R584_Hon-w4p5h6m1-3

Missing tremolos in upper wind parts

<img width="468" alt="Screen Shot 2020-01-27 at 3 08 43 PM" src="https://user-images.githubusercontent.com/54776443/73221981-0a3c5200-4117-11ea-9190-0c06d8a8937a.png">
<img width="843" alt="Screen Shot 2020-01-27 at 3 08 51 PM" src="https://user-images.githubusercontent.com/54776443/73221985-0c061580-4117-11ea-97aa-06022ec0262c.png">

**Comment by craigsapp** [comment]
Same as issue #18
