### ISSUE TITLE
Rendering Tuplets

### ISSUE THREAD

**Issue by epoudrier** [polyrhythm-project/polyrhythm-website#8]
R129, first measure, sextuplet with initial sixteenth rest shows "126" instead of "6"

**Comment by craigsapp** [comment]
Fixed:

https://polyrhythm.humdrum.org/example/?id=129

<img width="765" alt="Screen Shot 2019-12-31 at 21 17 29" src="https://user-images.githubusercontent.com/3487289/71638367-12d26300-2c13-11ea-976e-fd9d656c68b4.png">
