### ISSUE TITLE
Harmonics in string parts

### ISSUE THREAD

**Issue by annawright18** [polyrhythm-project/polyrhythm-website#82]
Harmonics in string parts not showing up (diamond notehead)

Example 534 - R534_Mai-w6p2m1-5

<img width="660" alt="Screen Shot 2020-01-31 at 2 54 51 PM" src="https://user-images.githubusercontent.com/54776443/73580264-c5c3f580-4439-11ea-8be5-dcb659341d43.png">
<img width="834" alt="Screen Shot 2020-01-31 at 2 54 59 PM" src="https://user-images.githubusercontent.com/54776443/73580265-c78db900-4439-11ea-9d66-6f21fbb0e7ce.png">

**Comment by craigsapp** [comment]
This is the same as issue #42 (these are also called fingered harmonics).

In the Sibelius pdf, the second cello part has fourths, but this is probably an error and the top note (C) should be a diamond shape).
