### ISSUE TITLE
Polyrhythm website scores vs. VHV scores

### ISSUE THREAD

**Issue by epoudrier** [polyrhythm-project/polyrhythm-website#9]
The score on polyrhythm website doesn't match the VHV score. For example, R129, first measure has a floating slur and the cello sextuplet with rest and notes in reverse order.

**Comment by craigsapp** [comment]
This was related to issue #8, so this issue should now be fixed as well.

It would be useful to give the URL to the specific example, and also to give a screenshot of the example along with the issue.

The screenshot can be done in MacOS by pressing command-shift-4, and then click-dragging the region to copy to an image on the desktop.  You can alternatively make a snapshot of an entire window by pressing command-shift-4 as before, but then press the space bar to go into window capture mode (after releasing command-shift-4).  Then click on the window to copy.
