### ISSUE TITLE
Single part

### ISSUE THREAD

**Issue by epoudrier** [polyrhythm-project/polyrhythm-website#90]
R308B, Falla, Flute, only a single part in the transcribed Suter example:
![Screen Shot 2020-02-02 at 3 40 55 PM](https://user-images.githubusercontent.com/15526880/73617343-7664fd00-45d2-11ea-91b5-e5d9db0bc37a.png)

We need to track down the full score and figure out whether there are missing parts; if so, the example should be edited to include all parts. If not, it will need to be excluded from analysis.

**Comment by craigsapp** [comment]
Here is the full score:

https://imslp.org/wiki/El_sombrero_de_tres_picos%2C_Suite_No.2_(Falla%2C_Manuel_de)
http://ks.imslp.net/files/imglnks/usimg/0/05/IMSLP579573-PMLP215154-TricorneSuite2.pdf

Page 13 (printed page number) at the start of rehearsal 10:

<img width="540" alt="Screen Shot 2020-02-02 at 19 10 46" src="https://user-images.githubusercontent.com/3487289/73622914-c69e8800-45ef-11ea-8dbf-3b15f28baa89.png">

There are strings on tremolos in a multi-level duple meter and brass doing sustains.

**Comment by epoudrier** [comment]
@Boardbreak there is a link to the full score for R308B here. In addition to adding the missing parts to the .sib file, please extract the example page, first page of unit, and any other pages necessary for tempo markings. Label all files with example number and reason for extracting.

**Comment by epoudrier** [comment]
R308B has been transcribed with full score by @Boardbreak 
It needs to be proofread (RDS SIB).
